- name: create a motd file
  hosts: all
  become: yes
  tasks:
    - lineinfile:
          line: Welcome to Proxy Server
          path: /etc/motd
          state: absent 
      when: "'proxy' in group_names"
    - lineinfile:
          line: Welcome to Apache server
          path: /etc/motd
          state: absent 
      when: "'webservers' in group_names"
    - lineinfile:
          line: Welcome to MySQL server
          path: /etc/motd
          state: absent 
      when: "'database' in group_names"
