- name: create a repo
  become: yes
  hosts: database
  tasks:
      - yum_repository:
           name: mysql56-community
           description: 'MySQL 5.6 YUM Repo'
           baseurl: http://repo.example.com/rpms
           state: present 
